(()=>{
'use strict';
const canvas=document.getElementById('gameCanvas');if(!canvas)return;const ctx=canvas.getContext('2d',{alpha:false});
const W=360,H=420,CX=180,CY=272,R=111,TAU=Math.PI*2,TOP=-Math.PI/2,HOP=.96,AIR=.73;
let state='idle',time=0,score=0,coinsTaken=0,combo=0,seed=1,rotation=0,gaps=[],coins=[],particles=[],rings=[],sound=false,audio;
let frameTime=0,visualTime=0,tickAt=-1,previousPhase=0,dpr=1,scale=1,ox=0,oy=0,pointer=null,previousX=0,keys=new Set(),leftHeld=false,rightHeld=false,fall=0,shake=0;
const norm=a=>((a%TAU)+TAU)%TAU,delta=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
const snap=()=>({state,score,time,coins:coinsTaken,combo,seed});
const emit=(n,d)=>window.dispatchEvent(new CustomEvent('planet:'+n,{detail:d}));
function rand(s){let a=s>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function hash(s){if(typeof s==='number'&&Number.isFinite(s))return s>>>0;let h=2166136261;for(const c of String(s||Date.now()))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0}
function resize(){const r=canvas.getBoundingClientRect(),w=r.width||W,h=r.height||H;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);scale=Math.min(w/W,h/H);ox=(w-W*scale)/2;oy=(h-H*scale)/2}
if(window.ResizeObserver)new ResizeObserver(resize).observe(canvas);window.addEventListener('resize',resize);canvas.style.touchAction='none';canvas.style.userSelect='none';resize();
function unlock(){if(!sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{})}catch(_){sound=false}}
function tone(f,d=.1,b=1){if(!sound||!audio||audio.state!=='running')return;try{const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*b),t+d);g.gain.setValueAtTime(.045,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+d+.01)}catch(_){}}
function clearInput(){pointer=null;keys.clear();leftHeld=false;rightHeld=false}
function start(s){seed=hash(s);const rng=rand(seed);state='running';time=0;score=0;coinsTaken=0;combo=0;rotation=0;gaps=[];coins=[];particles=[];rings=[];tickAt=-1;previousPhase=0;fall=0;shake=0;clearInput();for(let i=0;i<3;i++)gaps.push({a:.3+i*TAU/3+(rng()-.5)*.35,w:.22+rng()*.075});for(let i=0;i<20;i++)coins.push({a:i/20*TAU+.07,r:140+(i%3)*5,taken:false});unlock();tone(440,.12,1.5);frameTime=performance.now();emit('tick',snap());return snap()}
function pause(){if(state!=='running')return;clearInput();state='paused';emit('pause',snap())}
function resume(){if(state!=='paused')return;state='running';frameTime=performance.now();unlock()}
function burst(x,y,c,n){for(let i=0;i<n;i++){const a=Math.random()*TAU,v=30+Math.random()*130;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.4+Math.random()*.5,c})}}
function end(reason){if(state!=='running')return;state='ended';clearInput();if(reason==='fall'){fall=.01;shake=5;combo=0;tone(200,.3,.2);burst(CX,CY-R,'#FFB1A4',20);try{navigator.vibrate?.(55)}catch(_){}}else{tone(600,.25,1.5);burst(CX,CY-R-20,'#E8D578',50)}emit('tick',snap());emit('end',{...snap(),reason})}
canvas.addEventListener('pointerdown',e=>{if(state!=='running')return;e.preventDefault();pointer=e.pointerId;previousX=e.clientX;unlock();try{canvas.setPointerCapture(e.pointerId)}catch(_){}});
canvas.addEventListener('pointermove',e=>{if(state==='running'&&pointer===e.pointerId){e.preventDefault();const dx=Math.max(-90,Math.min(90,e.clientX-previousX));rotation+=dx/scale*.012;previousX=e.clientX}});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(pointer===e.pointerId)pointer=null});
function bind(id,direction){const el=document.getElementById(id);if(!el)return;el.style.touchAction='none';const set=v=>{if(direction<0)leftHeld=v;else rightHeld=v};el.addEventListener('pointerdown',e=>{if(state!=='running')return;e.preventDefault();set(true);unlock();try{el.setPointerCapture(e.pointerId)}catch(_){}});for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,()=>set(false))}bind('leftBtn',-1);bind('rightBtn',1);
window.addEventListener('keydown',e=>{if(state==='running'&&['ArrowLeft','ArrowRight','a','d'].includes(e.key)){e.preventDefault();keys.add(e.key)}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function hopHeight(t){const p=(t%HOP)/HOP;return p<AIR?Math.sin(p/AIR*Math.PI)*43:0}
function update(dt){time=Math.min(30,time+dt);rotation+=dt*(.48+(rightHeld||keys.has('ArrowRight')||keys.has('d')?2.3:0)-(leftHeld||keys.has('ArrowLeft')||keys.has('a')?2.3:0));const phase=(time%HOP)/HOP,height=hopHeight(time),landed=previousPhase<AIR&&phase>=AIR;previousPhase=phase;
if(landed){const local=norm(TOP-rotation),onGap=gaps.some(g=>Math.abs(delta(local,g.a))<g.w/2);if(time>3&&onGap){end('fall');return}rings.push({x:CX,y:CY-R+4,life:.35});tone(190,.035,1.2)}
const actorY=CY-R-height-10;for(const c of coins){if(c.taken)continue;const a=c.a+rotation,x=CX+Math.cos(a)*c.r,y=CY+Math.sin(a)*c.r;if(Math.hypot(x-CX,y-actorY)<23){c.taken=true;coinsTaken++;combo++;burst(x,y,'#F5D97C',10);tone(520+combo%7*80,.09,1.3);emit('coin',{coins:coinsTaken,combo});}}
if(coins.every(c=>c.taken)){for(const c of coins)c.taken=false;combo+=3}
score=coinsTaken*100+Math.floor(time*10);if(time>=30){end('win');return}if(time-tickAt>.07){tickAt=time;emit('tick',snap())}}
function round(x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h)}
function star(x,y,r){ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,s=i%2?r*.35:r;i?ctx.lineTo(x+Math.cos(a)*s,y+Math.sin(a)*s):ctx.moveTo(x+s,y)}ctx.closePath()}
function background(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#101A31');g.addColorStop(1,'#1D2940');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<37;i++){const x=(i*97+21)%W,y=(i*71+17)%H;ctx.globalAlpha=.15+.25*(1+Math.sin(visualTime+i))*.5;ctx.fillStyle='#D5E6F1';ctx.beginPath();ctx.arc(x,y,i%5===0?1.4:.75,0,TAU);ctx.fill()}ctx.globalAlpha=1;ctx.strokeStyle='#BBCBEA15';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(CX,CY,152,52,-.25,0,TAU);ctx.stroke();ctx.fillStyle='#080F1A';ctx.beginPath();ctx.ellipse(CX,398,108,12,0,0,TAU);ctx.fill()}
function world(rot,demo=false){ctx.save();ctx.translate(CX,CY);ctx.rotate(rot);const g=ctx.createRadialGradient(-35,-40,0,0,0,R);g.addColorStop(0,'#29555B');g.addColorStop(1,'#173344');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,R-3,0,TAU);ctx.fill();ctx.strokeStyle='#92E7CA13';ctx.lineWidth=1;for(const rr of [35,65,88]){ctx.beginPath();ctx.arc(0,0,rr,0,TAU);ctx.stroke()}ctx.beginPath();ctx.ellipse(0,0,39,R-5,0,0,TAU);ctx.stroke();ctx.beginPath();ctx.ellipse(0,0,R-5,38,0,0,TAU);ctx.stroke();
ctx.fillStyle='#6FB49A28';[[.4,48,21],[-1.8,65,19],[2.5,42,28]].forEach(([a,d,r])=>{ctx.beginPath();ctx.ellipse(Math.cos(a)*d,Math.sin(a)*d,r,r*.58,a,0,TAU);ctx.fill()});
const gs=demo?[{a:.3,w:.27},{a:2.4,w:.26},{a:4.5,w:.24}]:gaps;
ctx.lineWidth=11;ctx.strokeStyle='#94E4C6';ctx.shadowColor='#8DEBC6';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(0,0,R,0,TAU);ctx.stroke();ctx.shadowBlur=0;
for(const gap of gs){ctx.strokeStyle='#142032';ctx.lineWidth=16;ctx.beginPath();ctx.arc(0,0,R,gap.a-gap.w/2,gap.a+gap.w/2);ctx.stroke();ctx.strokeStyle='#FF9EAA';ctx.lineWidth=2;ctx.setLineDash([2,4]);ctx.beginPath();ctx.arc(0,0,R-10,gap.a-gap.w/2,gap.a+gap.w/2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#FFB4AC';for(const a of [gap.a-gap.w/2,gap.a+gap.w/2]){ctx.beginPath();ctx.arc(Math.cos(a)*R,Math.sin(a)*R,3,0,TAU);ctx.fill()}}
for(let i=0;i<10;i++){const a=i/10*TAU+.1;if(gs.some(g=>Math.abs(delta(a,g.a))<g.w))continue;ctx.save();ctx.rotate(a+Math.PI/2);ctx.translate(0,-R-4);if(i%3===0){ctx.fillStyle='#E9CA98';round(-6,-15,12,15,2);ctx.fill();ctx.fillStyle='#567086';ctx.fillRect(-3,-12,2,3);ctx.fillRect(1,-12,2,3);ctx.fillRect(-3,-6,2,3);ctx.fillRect(1,-6,2,3);ctx.fillStyle='#FFB399';ctx.beginPath();ctx.moveTo(-8,-15);ctx.lineTo(0,-21);ctx.lineTo(8,-15);ctx.closePath();ctx.fill()}else{ctx.strokeStyle='#A5B79B';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-12);ctx.stroke();ctx.fillStyle='#77BFA1';ctx.beginPath();ctx.arc(0,-13,5,0,TAU);ctx.fill()}ctx.restore()}
const cs=demo?Array.from({length:16},(_,i)=>({a:i/16*TAU,r:145,taken:false})):coins;for(const c of cs){if(c.taken)continue;const x=Math.cos(c.a)*c.r,y=Math.sin(c.a)*c.r;ctx.shadowColor='#F8D988';ctx.shadowBlur=10;ctx.fillStyle='#F8D988';ctx.beginPath();ctx.arc(x,y,5.7,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#B88648';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y-2.7);ctx.lineTo(x,y+2.7);ctx.stroke()}ctx.restore();
ctx.strokeStyle='#BDE5D91C';ctx.lineWidth=2;ctx.beginPath();ctx.arc(CX,CY,R+62,Math.PI*.12,Math.PI*.88);ctx.stroke();ctx.strokeStyle='#BDE5D9';ctx.beginPath();ctx.arc(CX,CY,R+62,Math.PI*.12,Math.PI*.12+(time/30)*Math.PI*.76);ctx.stroke()}
function worker(t,demo=false){const hop=hopHeight(t),y=CY-R-hop-10+fall*90;ctx.save();ctx.translate(CX,y);if(fall>0)ctx.rotate(fall*.8);ctx.fillStyle='#030A1855';if(!fall){ctx.save();ctx.translate(0,hop+10);ctx.scale(1,.25);ctx.beginPath();ctx.arc(0,0,10-hop*.08,0,TAU);ctx.fill();ctx.restore()}
const leg=Math.sin(t*17)*3;ctx.strokeStyle='#E3E6EA';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-3,8);ctx.lineTo(-5-leg,14);ctx.moveTo(3,8);ctx.lineTo(5+leg,14);ctx.stroke();ctx.fillStyle='#86A9C2';round(-7,-4,14,14,3);ctx.fill();ctx.fillStyle='#F3ECE0';ctx.beginPath();ctx.moveTo(-3,-3);ctx.lineTo(3,-3);ctx.lineTo(0,4);ctx.closePath();ctx.fill();ctx.strokeStyle='#F5B8A0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,5);ctx.stroke();ctx.strokeStyle='#86A9C2';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-6,0);ctx.lineTo(-11,5-leg);ctx.moveTo(6,0);ctx.lineTo(11,3+leg);ctx.stroke();ctx.fillStyle='#C9A88D';round(9,3+leg,8,7,1.5);ctx.fill();ctx.strokeStyle='#E9CDAF';ctx.lineWidth=1;round(11,1+leg,4,3,1);ctx.stroke();ctx.fillStyle='#F4DFC2';ctx.beginPath();ctx.arc(0,-11,9.5,0,TAU);ctx.fill();ctx.fillStyle='#3D3B43';ctx.beginPath();ctx.arc(-1,-14,9,Math.PI,TAU);ctx.fill();ctx.fillRect(-9,-15,3,6);ctx.fillStyle='#293749';ctx.beginPath();ctx.arc(-3,-11,1,0,TAU);ctx.arc(3,-11,1,0,TAU);ctx.fill();ctx.strokeStyle='#293749';ctx.lineWidth=1;ctx.beginPath();if(fall>0)ctx.arc(0,-6,2,0,TAU);else ctx.arc(0,-8,3,.2,Math.PI-.2);ctx.stroke();ctx.restore();
if(time<3&&state==='running'){ctx.strokeStyle='#FFF2AE70';ctx.setLineDash([3,4]);ctx.lineWidth=1;ctx.beginPath();ctx.arc(CX,y-4,23,0,TAU);ctx.stroke();ctx.setLineDash([])}}
function render(){ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#101A31';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.setTransform(dpr*scale,0,0,dpr*scale,ox*dpr,oy*dpr);ctx.save();ctx.beginPath();ctx.rect(0,0,W,H);ctx.clip();if(shake>.1)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);background();const demo=state==='idle';world(demo?visualTime*.25:rotation,demo);worker(demo?visualTime:time,demo);for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.c;star(p.x,p.y,2.2);ctx.fill()}for(const r of rings){ctx.globalAlpha=r.life*2;ctx.strokeStyle='#B6EAD1';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(r.x,r.y,5+(1-r.life)*12,2+(1-r.life)*2,0,0,TAU);ctx.stroke()}ctx.globalAlpha=1;ctx.restore()}
function frame(now){const dt=Math.min(.033,Math.max(0,(now-(frameTime||now))/1000));frameTime=now;if(state!=='paused'){visualTime+=dt;if(state==='running')update(dt);if(fall>0)fall=Math.min(1.2,fall+dt*2.5);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=80*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);rings.forEach(r=>r.life-=dt);rings=rings.filter(r=>r.life>0);shake=Math.max(0,shake-dt*20)}render();requestAnimationFrame(frame)}
window.PlanetGame={start,pause,resume,setSound(v){sound=Boolean(v);if(sound)unlock();return sound},getState:snap};requestAnimationFrame(frame);
})();
